# Generated by Django 4.1 on 2022-09-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_amenity_facility_houserule_housetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='house_photos'),
        ),
    ]
