# Generated by Django 4.1 on 2022-09-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_photo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='room',
            new_name='house',
        ),
    ]
