# Generated by Django 4.1.1 on 2022-09-17 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_rename_room_photo_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
