# Generated by Django 4.1 on 2022-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room',
            new_name='house',
        ),
    ]
