# Generated by Django 4.1 on 2022-09-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='rooms',
            new_name='houses',
        ),
    ]
